name: Build and Deploy .NET App to Azure

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x' # change based on your project version

      - name: Restore dependencies
        run: dotnet restore
        working-directory: backend/CodeEditorBackend

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: backend/CodeEditorBackend

      - name: Publish with dotnet
        run: dotnet publish -c Release -o publish
        working-directory: backend/CodeEditorBackend

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: backend/CodeEditorBackend/publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'zainab-codeeditor'
          slot-name: 'Production'
          package: ./app
