  - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: backend/CodeEditorBackend

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"
        working-directory: backend/CodeEditorBackend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
@@ -38,25 +40,25 @@ jobs:
  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
@@ -65,4 +67,3 @@ jobs:
          app-name: 'zainab-codeeditor'
          slot-name: 'Production'
          package: .

